#!/bin/bash

set -e

source functions

function freestandinggcc(){

    cd ${BUILD_DIR}

    test -d  gcc-4.7.3 && /bin/rm -rf gcc-4.7.3
    tar -xf ${SOURCE_DIR}/gcc-4.7.3.tar.bz2

    cd gcc-4.7.3/

    tar -xf ${SOURCE_DIR}/gmp-5.0.5.tar.bz2
    test -d gmp &&  /bin/rm -rf gmp
    /bin/mv -f  gmp-5.0.5 gmp

    tar -xf ${SOURCE_DIR}/mpfr-3.1.1.tar.bz2  
    test -d mpfr && /bin/rm -rf mpfr
    /bin/mv -f  mpfr-3.1.1 mpfr

    tar -xf ${SOURCE_DIR}/mpc-1.0.1.tar.gz
    test -d mpc && /bin/rm -rf mpc
    /bin/mv -f  mpc-1.0.1 mpc

    test -d ${BUILD_DIR}/gcc-build && /bin/rm -rf ${BUILD_DIR}/gcc-build
    mkdir ${BUILD_DIR}/gcc-build  && cd ${BUILD_DIR}/gcc-build

    CC=/usr/local/Cellar/gcc@7/7.5.0_3/bin/gcc-7 ../gcc-4.7.3/configure  --disable-werror \
                --prefix=$CROSS_GCC_TMP \
                --target=$TARGET \
                --with-sysroot=$SYSROOT \
                --with-newlib \
                --enable-languages=c \
                --with-mpfr-include=${BUILD_DIR}/gcc-4.7.3/mpfr/src \
                --with-mpfr-lib=${BUILD_DIR}/gcc-build/mpfr/src/.libs \
                --disable-shared --disable-threads \
                --disable-decimal-float --disable-libquadmath \
                --disable-libmudflap --disable-libgomp \
                --disable-nls --disable-libssp 2>&1 | tee log.configure.gcc

    make ${SPEEDUP} 2>&1 | tee log.make.gcc

    make ${SPEEDUP} install 2>&1 | tee log.makeinstall.gcc

    cd $CROSS_GCC_TMP
    ln -sfv libgcc.a lib/gcc/i686-none-linux-gnu/4.7.3/libgcc_eh.a  

    echogreen "ls $CROSS_GCC_TMP"
    ls $CROSS_GCC_TMP/

    echogreen "### finish freestanding gcc build"
}

freestandinggcc
