#!/bin/bash

set -e

source functions

function kernelheaders(){
	cd ${BUILD_DIR}
	test -d linux-3.7.4 && /bin/rm -rf linux-3.7.4
	tar -xf ${SOURCE_DIR}/linux-3.7.4.tar.xz

	cd ${BUILD_DIR}/linux-3.7.4
	make mrproper 2>&1 | tee log.mrproper

	make ARCH=i386 headers_check 2>&1  | tee log.make.headers_check

	make defconfig

	make ARCH=i386 INSTALL_HDR_PATH=$SYSROOT/usr/  headers_install ${SPEEDUP} 2>&1 | tee log.make.headers

	echogreen "ls $SYSROOT/usr/include"
	ls $SYSROOT/usr/include
	echogreen "### finish kernel head build"

}

kernelheaders